config/routes.rb
Rails.application.routes.draw do
scope module: :public do
  get 'customers/edit', to: 'customers#edit'
  patch 'customers' , to: 'customers#update'

  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch '/customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'

  # get  '/customers/unsubscribe' => 'customers#unsubscribe'
  # patch  '/customers/withdraw' => 'customers#withdraw'

end
# 顧客用
# URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
  sessions: "public/sessions",
  registrations: "public/registrations",
}

root to: "public/homes#top"
    get '/about', to: 'public/homes#about', as: 'about'

  scope module: :public do
    get 'customers/my_page', to: 'customers#show'
    # get 'customers/edit', to: 'customers#edit'
    get 'customers/unsubscribe', to:'customers#unsubscribe'
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    post 'orders/confirm', to: 'orders#confirm'
    get 'orders/thanks', to: 'orders#thanks'
    # resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :cart_items, only: [:create, :index, :update, :destroy, :destroy_all]
    resources :orders, only: [:new, :index, :show, :create]
    resources :registrations, only: [:new, :create]

  end


# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
    get 'admin/new', to: 'admin#new'

# root 'admin_login#new'
  namespace :admin do
    # get '/admin', to: redirect('/admin/genres')
    root to: "homes#top"
    # get 'homes/top', to: 'admin'
    resources :genres, only: [:new, :create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :homes, only: [:top]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]

  end


# resources :public, only: [:show, :edit]

  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
# devise :database_authenticatable, :registerable,
#   :recoverable, :rememberable, :validatable

  belongs_to :item
  belongs_to :customer

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

    # 小計を求めるメソッド
    def subtotal
        item.with_tax_price * amount
    end

    def with_tax_price
      (price * 1.1).floor
    end



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :cart_items
 has_many :addresses
 has_many :orders

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

 has_many :items

end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  has_many :items, through: :order_details
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  def address_display
  '〒' + post_code + ' ' + address + ' ' + name
  end

  enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, preparation_for_shipping: 3, sent: 4 }


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status:{making_unable: 0, waiting_for_making: 1, in_making: 2, making_completed: 3 }

end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
    @customer = Customer.new
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
     redirect_to admin_customer_path(@customer)
    end
  end

   # 投稿データのストロングパラメータ
  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :address, :postal_code, :telephone_number, :email)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!

def top
  @home = Home.new
  @homes = Home.all
#   @customer = Customer.find(params[:id])
  @orders = Order.all
end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.genre_id = 1
   if @item.save!
    redirect_to admin_item_path(@item)
   else
    redirect_to root_path
   end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item)
    end
  end

  def index
    @items = Item.all
    @item = Item.new
  end

  def show
     @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  # 投稿データのストロングパラメータ
  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

# before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

 

  protected




  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path

    when Customer
      root_path
    else
      root_path
    end
  end


end

app/controllers/custom_devise_controller.rb
# class CustomDeviseController < ApplicationController
# end

class CustomDeviseController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    # サインイン後の遷移先を指定します
    # 例えば、管理者専用のダッシュボードページを指定する場合は、以下のようになります
    admin_dashboard_path
  end

  def after_sign_out_path_for(resource)
    # サインアウト後の遷移先を指定します
    # 例えば、トップページにリダイレクトする場合は、以下のようになります
    root_path
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_devise_helper.rb
module CustomDeviseHelper
end

app/views/admin/customers/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @customer, url: admin_customer_path do |f| %>

  <label for="inputName">氏名</label>
  <p><%= f.text_field :first_name, autofocus: true, id:"inputName", placeholder:"名前"%>　  <%= f.text_field :last_name, autofocus: true, id:"inputName", placeholder:"名前"%></p>

  <label for="inputName">フリガナ</label>
  <p><%= f.text_field :first_name_kana, autofocus: true, id:"inputName", placeholder:"名前"%>　  <%= f.text_field :last_name_kana, autofocus: true, id:"inputName", placeholder:"名前"%></p>

  <label for="inputName">郵便番号</label>
  <p><%= f.text_field :postal_code, autofocus: true, id:"inputName", placeholder:"名前"%></p>

 <label for="inputName">住所</label>
  <p><%= f.text_field :address, autofocus: true, id:"inputName", placeholder:"名前"%></p>

  <label for="inputName">電話番号</label>
  <p><%= f.text_field :telephone_number, autofocus: true, id:"inputName", placeholder:"名前"%></p>

 <label for="inputName">メールアドレス</label>
  <p><%= f.text_field :email, autofocus: true, id:"inputName", placeholder:"名前"%></p>

  <!--<label for="inputImage">ProfileImage</label>-->
  <!--<#%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>-->
  <%= f.submit "変更を保存" %>
<% end %>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
 <div class="col-md-8" style="background-color: ">

  <h1>会員一覧</h1>

  <%#= link_to admin_customer_path(customer.id) do %>
  <%# end %>
 <table class="table">
  <thead>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
  </thead>

  <% @customers.each do |customer| %>
  <tbody>
   <td> <%= customer.id %> </td>
   <td> <%= link_to admin_customer_path(customer.id) do %> <%= customer.first_name %> <%= customer.last_name %></td> <% end %>
   <td> <%= customer.email %></td>
   <td><%if customer.is_active == true %>
   <p>有効</p>
   <% else %><p>無効</p><% end %></td>
   <%#= link_to "詳細", edit_admin_customer_path %>

<% end %>

app/views/admin/customers/show.html.erb
<h1>会員詳細</h1>
   <p>会員ID:  <%= @customer.id %></p>
   <p>氏名： <%= @customer.first_name %> <%= @customer.last_name %></p>
   <p>カナ： <%= @customer.first_name_kana %> <%= @customer.last_name_kana %></p>
   <p>郵便番号： <%= @customer.postal_code %></p>
   <p>住所： <%= @customer.address %></p>
   <p>電話番号： <%= @customer.telephone_number %></p>
   <p>メールアドレス： <%= @customer.email %></p>
   <p>会員ステータス:  <%= @customer.is_active_i18n %></p>
   <%= link_to "編集",  edit_admin_customer_path %>