config/routes.rb
Rails.application.routes.draw do
scope module: :public do
  get 'customers/edit', to: 'customers#edit'
  patch 'customers' , to: 'customers#update'

  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch '/customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'

  # get  '/customers/unsubscribe' => 'customers#unsubscribe'
  # patch  '/customers/withdraw' => 'customers#withdraw'

end
# 顧客用
# URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
  sessions: "public/sessions",
  registrations: "public/registrations",
}

root to: "public/homes#top"
    get '/about', to: 'public/homes#about', as: 'about'

  scope module: :public do
    get 'customers/my_page', to: 'customers#show'
    # get 'customers/edit', to: 'customers#edit'
    get 'customers/unsubscribe', to:'customers#unsubscribe'
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all'
    post 'orders/confirm', to: 'orders#confirm'
    get 'orders/thanks', to: 'orders#thanks'
    # resources :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :cart_items, only: [:create, :index, :update, :destroy, :destroy_all]
    resources :orders, only: [:new, :index, :show, :create]
    resources :registrations, only: [:new, :create]

  end


# 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
    get 'admin/new', to: 'admin#new'

# root 'admin_login#new'
  namespace :admin do
    # get '/admin', to: redirect('/admin/genres')
    root to: "homes#top"
    # get 'homes/top', to: 'admin'
    resources :genres, only: [:new, :create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :homes, only: [:top]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]

  end


# resources :public, only: [:show, :edit]

  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
# devise :database_authenticatable, :registerable,
#   :recoverable, :rememberable, :validatable

  belongs_to :item
  belongs_to :customer

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

    # 小計を求めるメソッド
    def subtotal
        item.with_tax_price * amount
    end

    def with_tax_price
      (price * 1.1).floor
    end



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :cart_items
 has_many :addresses
 has_many :orders

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

 has_many :items

end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  # 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  has_many :items, through: :order_details
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  def address_display
  '〒' + post_code + ' ' + address + ' ' + name
  end

  enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, preparation_for_shipping: 3, sent: 4 }


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status:{making_unable: 0, waiting_for_making: 1, in_making: 2, making_completed: 3 }

end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

# before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

 

  protected




  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path

    when Customer
      root_path
    else
      root_path
    end
  end


end

app/controllers/custom_devise_controller.rb
# class CustomDeviseController < ApplicationController
# end

class CustomDeviseController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    # サインイン後の遷移先を指定します
    # 例えば、管理者専用のダッシュボードページを指定する場合は、以下のようになります
    admin_dashboard_path
  end

  def after_sign_out_path_for(resource)
    # サインアウト後の遷移先を指定します
    # 例えば、トップページにリダイレクトする場合は、以下のようになります
    root_path
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_devise_helper.rb
module CustomDeviseHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/xxxxxxxxxx.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <ul class="navbar-nav ml-auto">

    <li class="nav-item">
        ながのCAKE
     </li>

    <% if customer_signed_in? %>
    <ul class="navbar-nav ml-auto">
    <li>
      <%= link_to "マイページ　", customers_my_page_path %>
    </li>
    <li>
      <%= link_to "商品一覧　",  items_path %>
    </li>
    <li>
      <%= link_to "カート　", cart_items_path %>
    </li>
    <li>
      <%= link_to "ログアウト　", destroy_customer_session_path, method: :delete %>
    </li>

    </ul>


        <% elsif admin_signed_in? %>

      <li>
        <%= link_to "会員一覧　", admin_customers_path %>
      </li>
      <!--<li>-->
      <!--  <%#= link_to '投稿フォーム', new_admin_item_path %>-->
      <!--</li>-->

      <li>
        <%= link_to "商品一覧　", admin_items_path %>
      </li>

      <li>
        <%= link_to "注文履歴一覧　", admin_root_path %>
      </li>

      <li>
        <%= link_to "ジャンル一覧　", admin_genres_path %>
      </li>


      <li>
        <%= link_to "adminログアウト　", destroy_admin_session_path, method: :delete %>
      </li>

        <% else %>
      <li>
        <%= link_to "About　", about_path %>
      </li>
      <li>
        <%= link_to "商品一覧　", items_path %>
      </li>

      <li>
        <%= link_to "新規登録　", new_customer_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン　", new_customer_session_path %>
      </li>

    <% end %>
    </header>
    <%= yield %>


    </ul>
  </div>

  </body>




</html>